#!/usr/bin/env node
/**
 * publish-dromx.mjs — assemble the ONE npm-publishable dromx-code package.
 *
 * Produces: publish/dromx-code/ — the CLI (rebranded coding-agent dist) WITH
 * the pi-loopx extension bundled (examples/extensions/loopx/) and a postinstall
 * that auto-registers the extension. So `npm i -g dromx-code.tgz` gives users
 * the CLI + /auto-loop in ONE install (no separate `dromx install` step).
 *
 * The monorepo's internal package name (@earendil-works/pi-coding-agent) is
 * left untouched; this re-packages the built output under `dromx-code`.
 *
 * Prereq: `npm run build` (so packages/coding-agent/dist/cli.js exists).
 *
 * Usage:
 *   npm run build
 *   node scripts/publish-dromx.mjs
 *   cd publish/dromx-code && npm pack    # → dromx-code-<version>.tgz
 */
import { readFileSync, writeFileSync, cpSync, mkdirSync, existsSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = join(__dirname, "..");
const CA = join(REPO, "packages", "coding-agent");
const PUB = join(REPO, "publish");

const caPkg = JSON.parse(readFileSync(join(CA, "package.json"), "utf8"));

function writePkg(dir, obj) {
	writeFileSync(join(dir, "package.json"), JSON.stringify(obj, null, "\t") + "\n");
}
function copyTree(src, dest) {
	if (!existsSync(src)) return false;
	rmSync(dest, { recursive: true, force: true });
	cpSync(src, dest, { recursive: true });
	return true;
}

// --- dromx-code (the CLI + bundled pi-loopx extension) ----------------------
const codeDir = join(PUB, "dromx-code");
if (!existsSync(join(CA, "dist", "cli.js"))) {
	console.error("ERROR: packages/coding-agent/dist/cli.js not found. Run `npm run build` first.");
	process.exit(1);
}
if (!existsSync(join(CA, "examples", "extensions", "loopx", "index.ts"))) {
	console.error("ERROR: pi-loopx extension not found at packages/coding-agent/examples/extensions/loopx/index.ts");
	process.exit(1);
}
mkdirSync(codeDir, { recursive: true });
copyTree(join(CA, "dist"), join(codeDir, "dist"));
copyTree(join(CA, "examples"), join(codeDir, "examples")); // includes extensions/loopx (bundled) + other samples
copyTree(join(CA, "docs"), join(codeDir, "docs"));
if (existsSync(join(CA, "npm-shrinkwrap.json"))) {
	cpSync(join(CA, "npm-shrinkwrap.json"), join(codeDir, "npm-shrinkwrap.json"));
}
writePkg(codeDir, {
	name: "dromx-code",
	version: caPkg.version,
	description: "DromX — an autonomous coding agent (improved pi-mono) with loopx-powered auto-loop and real-browser control. Bundles the loopx (/auto-loop) and webbridge (/webbridge) extensions and auto-registers them on install.",
	type: "module",
	bin: { dromx: "dist/cli.js" },
	main: "dist/index.js",
	types: "dist/index.d.ts",
	exports: caPkg.exports,
	scripts: {
		// Auto-register all DromX extensions on `npm i -g` so every feature (auto-loop,
		// webbridge, web search, code diagnostics, memory, subagents, MCP, ...) works out
		// of the box. postinstall.mjs installs each one best-effort (a failure warns, never
		// aborts the install). npm packages need network; the bundled loopx/webbridge don't.
		postinstall: "node postinstall.mjs || true",
	},
	files: ["dist", "examples", "docs", "postinstall.mjs", "CHANGELOG.md", "npm-shrinkwrap.json"],
	piConfig: { name: "dromx", configDir: ".pi" },
	engines: caPkg.engines ?? { node: ">=22.19.0" },
	dependencies: caPkg.dependencies,
	overrides: caPkg.overrides,
	keywords: ["coding-agent", "ai", "cli", "loopx", "autonomous", "pi", "dromx"],
	license: "MIT",
});

// Generate postinstall.mjs — installs every DromX extension best-effort on `npm i -g`.
// Bundled (loopx, webbridge) install from local ./examples; the rest come from npm/git.
// Keep this list in sync with scripts/setup-dromx.sh.
const EXT_SOURCES = [
	"./examples/extensions/loopx", // bundled
	"./examples/extensions/webbridge", // bundled
	"npm:pi-mcp-adapter",
	"npm:pi-hashline-edit",
	"npm:pi-web-access",
	"npm:pi-lens",
	"npm:pi-hermes-memory",
	"git:github.com/nicobailon/pi-subagents",
	"git:github.com/nicobailon/pi-messenger",
	"git:github.com/nicobailon/pi-intercom",
];
writeFileSync(
	join(codeDir, "postinstall.mjs"),
	`#!/usr/bin/env node
// Auto-generated by scripts/publish-dromx.mjs — installs DromX extensions after \`npm i -g\`.
// Best-effort: each install runs independently; a failure warns but never aborts.
import { spawnSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const cli = join(here, "dist", "cli.js");
const sources = ${JSON.stringify(EXT_SOURCES, null, "\t")};

console.log("DromX: registering extensions (this may take a minute; npm packages need network)...");
let failed = [];
for (const src of sources) {
	const r = spawnSync(process.execPath, [cli, "install", src, "--no-approve"], {
		cwd: here,
		stdio: "ignore",
		env: { ...process.env, PI_OFFLINE: "1" },
		timeout: 180000,
	});
	if (r.status === 0) {
		console.log("  \\u2713 " + src);
	} else {
		failed.push(src);
		console.log("  \\u26a0 " + src + " (skipped)");
	}
}
if (failed.length) {
	console.log("\\nDromX: some extensions were skipped. Install them later with:");
	for (const src of failed) console.log("  dromx install " + src);
}
console.log("DromX: done. Run 'dromx' to start; '/login' to add an API key.");
`,
);
console.log("✓ wrote publish/dromx-code/postinstall.mjs (registers " + EXT_SOURCES.length + " extensions)");
console.log("✓ assembled publish/dromx-code  (bin: dromx, version:", caPkg.version + ")");

console.log(`
Distribute without an npm registry (share the ONE tarball with your internal group):

  cd publish/dromx-code && npm pack    # → dromx-code-${caPkg.version}.tgz

Internal users install (ONE npm install — postinstall registers ALL extensions:
auto-loop, webbridge, web search, code diagnostics, memory, subagents, MCP, ...):
  npm i -g ./dromx-code-${caPkg.version}.tgz   # needs network to pull the npm/git extensions
  dromx                                         # run; then /login to add an API key

Optional extras (only if you use those features):
  /auto-loop  — needs loopx; first run offers to auto-install it (needs Python 3)
  /webbridge  — needs the WebBridge daemon + Chrome extension; /webbridge guides you through it

If some extensions were skipped (postinstall prints which), re-run:
  dromx install <source>   # e.g. dromx install npm:pi-lens

(To publish to a public/private registry instead: cd publish/dromx-code && npm publish)
`);
